#!/usr/bin/env python3
"""Generated by `lc load` — regenerate with `lc load <task_id>` rather than editing.

Runs the problem's test cases against solution.py and prints one JSON object per
line so the `lc` CLI can render results. Also usable standalone:

    python run_tests.py            # all recorded cases
    python run_tests.py --case 3   # a single case (1-indexed)
    python run_tests.py --full     # the original full assert suite
    python run_tests.py --stop-on-first-failure   # quit at the first failing case

Exit code: 0 if everything passed, 1 otherwise.
"""
import argparse
import ast
import importlib.util
import io
import json
import os
import sys
import traceback
from contextlib import redirect_stdout

HERE = os.path.dirname(os.path.abspath(__file__))
MAX_STDOUT = 2000

TEST_PREAMBLE = (
    "from typing import *\n"
    "import collections, functools, heapq, itertools, math, bisect, re, string\n"
)


def emit(obj):
    sys.stdout.write(json.dumps(obj) + "\n")
    sys.stdout.flush()


def load_meta():
    with open(os.path.join(HERE, ".lc", "meta.json"), encoding="utf-8") as fh:
        return json.load(fh)


def load_solution():
    path = os.path.join(HERE, "solution.py")
    spec = importlib.util.spec_from_file_location("solution", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["solution"] = mod
    spec.loader.exec_module(mod)
    return mod


def clean_entry_point(raw):
    """Strip `Solution().foo()` / `sol.foo()` down to the bare method name."""
    if not raw:
        return raw
    s = raw.strip()
    stripped = False
    for prefix in ("Solution().", "Solution.", "sol."):
        if s.startswith(prefix):
            s = s[len(prefix) :].strip()
            stripped = True
            break
    if not stripped and "." in s:
        method = s.rsplit(".", 1)[-1].strip()
        name = method.split("(", 1)[0].strip()
        if name and all(c.isalnum() or c == "_" for c in name):
            s = name
    if "(" in s:
        name = s.split("(", 1)[0].strip()
        if name and all(c.isalnum() or c == "_" for c in name):
            s = name
    return s


def instantiate(cls):
    """`KthLargest(k, nums)` needs constructor args; sample cases still call `add`."""
    try:
        return cls()
    except TypeError:
        return cls.__new__(cls)


def resolve_candidate(mod, entry_point):
    entry_point = clean_entry_point(entry_point)
    if entry_point:
        sol_cls = getattr(mod, "Solution", None)
        if sol_cls is not None and hasattr(sol_cls, entry_point):
            return getattr(instantiate(sol_cls), entry_point)
        if hasattr(mod, entry_point):
            return getattr(mod, entry_point)
        for name, obj in vars(mod).items():
            if (
                isinstance(obj, type)
                and not name.startswith("_")
                and hasattr(obj, entry_point)
            ):
                return getattr(instantiate(obj), entry_point)
        raise AttributeError(
            "cannot find entry point %r as a Solution method or module-level function"
            % entry_point
        )
    sol_cls = getattr(mod, "Solution", None)
    if sol_cls is not None:
        methods = [m for m in vars(sol_cls) if not m.startswith("_")]
        if len(methods) == 1:
            return getattr(instantiate(sol_cls), methods[0])
    raise AttributeError("no entry point recorded, and none could be guessed")


def parse_input(text):
    """Parse 'n = 7, queries = [[0, 5]]' (or bare positional literals) into (args, kwargs)."""
    tree = ast.parse("__lc__(%s)" % text, mode="eval")
    call = tree.body
    args = [ast.literal_eval(node) for node in call.args]
    kwargs = {kw.arg: ast.literal_eval(kw.value) for kw in call.keywords}
    return args, kwargs


def parse_expected(text):
    stripped = text.strip()
    try:
        return ast.literal_eval(stripped), True
    except (ValueError, SyntaxError, MemoryError, RecursionError):
        pass
    if stripped in ("true", "false"):
        return stripped == "true", True
    if stripped == "null":
        return None, True
    return text, False


def normalize(value):
    if isinstance(value, tuple):
        value = list(value)
    if isinstance(value, list):
        return [normalize(v) for v in value]
    return value


def compare(actual, expected):
    a, e = normalize(actual), normalize(expected)
    if isinstance(a, float) or isinstance(e, float):
        try:
            return abs(float(a) - float(e)) < 1e-6
        except (TypeError, ValueError):
            pass
    return a == e


def run_case(mod, meta, idx, case):
    result = {
        "case": idx,
        "pass": False,
        "input": case.get("input", ""),
        "expected": case.get("output", ""),
        "actual": None,
        "error": None,
        "stdout": None,
    }
    try:
        candidate = resolve_candidate(mod, meta.get("entry_point"))
        args, kwargs = parse_input(case.get("input", ""))
        buf = io.StringIO()
        with redirect_stdout(buf):
            actual = candidate(*args, **kwargs)
        result["stdout"] = buf.getvalue()[:MAX_STDOUT] or None
        expected, parsed = parse_expected(case.get("output", ""))
        if parsed:
            ok = compare(actual, expected)
        else:
            ok = str(actual) == case.get("output", "").strip()
        result["pass"] = bool(ok)
        result["actual"] = repr(actual)
    except Exception:
        result["error"] = traceback.format_exc(limit=8)
    return result


def run_full_suite(mod, meta):
    result = {
        "case": 0,
        "suite": True,
        "pass": False,
        "input": "<full assert suite>",
        "expected": "all asserts pass",
        "actual": None,
        "error": None,
        "stdout": None,
    }
    test_src = (meta.get("test") or "").strip()
    if not test_src:
        result["error"] = "this problem has no `test` field to fall back on"
        emit(result)
        return False
    namespace = {"__name__": "__lc_test__"}
    # LC+Tests constructor-style asserts (`Solution(1, 1).flip()`) look up
    # Solution / TreeNode in this namespace, not via `candidate`. Preamble
    # does not import solution.py; copy public names so check() can see them.
    for name, obj in vars(mod).items():
        if not name.startswith("_"):
            namespace.setdefault(name, obj)
    try:
        exec(compile(TEST_PREAMBLE + test_src, "<lc-test-suite>", "exec"), namespace)
        check = namespace.get("check")
        buf = io.StringIO()
        if check is not None:
            candidate = resolve_candidate(mod, meta.get("entry_point"))
            with redirect_stdout(buf):
                check(candidate)
            result["actual"] = "all asserts passed"
        else:
            # pytest-style suites (KodCode and friends) define `test_*`
            # functions and import from `solution`, which `load_solution` has
            # already registered in sys.modules. Run them in declaration order;
            # there is no pytest here, so no fixtures are supported.
            tests = [
                (name, fn)
                for name, fn in namespace.items()
                if name.startswith("test_") and callable(fn)
            ]
            if not tests:
                raise RuntimeError(
                    "the test suite defines neither check(candidate) nor any test_* function"
                )
            with redirect_stdout(buf):
                for _, fn in tests:
                    fn()
            result["actual"] = "%d test function(s) passed" % len(tests)
        result["stdout"] = buf.getvalue()[:MAX_STDOUT] or None
        result["pass"] = True
    except Exception:
        result["error"] = traceback.format_exc(limit=8)
    emit(result)
    return result["pass"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", type=int, default=None, help="run one case (1-indexed)")
    parser.add_argument("--full", action="store_true", help="run the original assert suite")
    parser.add_argument(
        "--stop-on-first-failure",
        action="store_true",
        help="stop after the first failing case instead of running them all",
    )
    opts = parser.parse_args()

    sys.setrecursionlimit(10000)
    meta = load_meta()
    try:
        mod = load_solution()
    except Exception:
        emit({
            "case": 0,
            "pass": False,
            "input": "<import solution.py>",
            "expected": "module imports cleanly",
            "actual": None,
            "error": traceback.format_exc(limit=8),
            "stdout": None,
        })
        sys.exit(1)

    cases = meta.get("cases") or []
    if opts.full or not cases:
        sys.exit(0 if run_full_suite(mod, meta) else 1)

    selected = list(enumerate(cases, start=1))
    if opts.case is not None:
        selected = [(i, c) for i, c in selected if i == opts.case]
        if not selected:
            emit({
                "case": opts.case,
                "pass": False,
                "input": "",
                "expected": "",
                "actual": None,
                "error": "case %d does not exist (valid: 1..%d)" % (opts.case, len(cases)),
                "stdout": None,
            })
            sys.exit(1)

    all_ok = True
    for idx, case in selected:
        res = run_case(mod, meta, idx, case)
        emit(res)
        all_ok = all_ok and res["pass"]
        # Settings → Tests. The cases already emitted still reach the results
        # panel; the ones after the failure are simply never run.
        if not res["pass"] and opts.stop_on_first_failure:
            break
    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
