/**
 * Apply the Android overlay to the generated Gradle project.
 *
 * `src-tauri/gen/android/` is generated by `tauri android init` and is not in
 * git. `android:apk:practice` / `android:apk:whiteboard` / `android:dev` /
 * `android-install-practice.cmd` call this first, so
 * a missing project runs `tauri android init --ci` instead of failing with a
 * "run init first" message.
 *
 * After init (or on every later build) the edits:
 *
 *   1. copy `android-overlay/network_security_config.xml` into the project's
 *      `res/xml/`,
 *   2. point the manifest's `<application>` at it, and
 *   3. rewrite generated `BuildTask.kt` so it uses `ExecOperations` instead of
 *      deprecated `Project.exec` (Gradle 8.11+ warning, gone in 9).
 *   4. pin `buildSrc` Kotlin compile to JVM 17 so a JDK 23 Gradle does not
 *      emit "Kotlin does not yet support 23 JDK target".
 *   5. pin `org.gradle.java.home` to a JDK 17–24. Android Studio's JBR is now
 *      25.0.2; Gradle 8.14 + Kotlin 1.9 fail configuring `:buildSrc` with
 *      that version as the entire error message.
 *
 * Without (1)+(2) Android 9+ blocks the WebView's cleartext HTTP fetches to
 * external http:// pages (Annotate mode). The harness router itself is in-process.
 *
 * Idempotent: running it twice is a no-op, so it is safe to chain in front of
 * `tauri android dev` / `build`.
 */

import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(APP_DIR, "src-tauri", "android-overlay", "network_security_config.xml");
const PROJECT = join(APP_DIR, "src-tauri", "gen", "android");
const RES_XML = join(PROJECT, "app", "src", "main", "res", "xml");
const MANIFEST = join(PROJECT, "app", "src", "main", "AndroidManifest.xml");

const ATTRIBUTE = 'android:networkSecurityConfig="@xml/network_security_config"';

/**
 * Add the `networkSecurityConfig` attribute to `<application>`.
 *
 * Returns the manifest unchanged when the attribute is already there, so the
 * script can run before every build without accumulating duplicates.
 *
 * @param {string} manifest raw AndroidManifest.xml
 * @returns {string}
 */
export function withNetworkSecurityConfig(manifest) {
  if (manifest.includes("android:networkSecurityConfig")) return manifest;
  const opening = /<application\b/.exec(manifest);
  if (!opening) {
    throw new Error("AndroidManifest.xml has no <application> tag — is the project generated?");
  }
  const at = opening.index + opening[0].length;
  return `${manifest.slice(0, at)}\n        ${ATTRIBUTE}${manifest.slice(at)}`;
}

/**
 * Swap Tauri's generated `project.exec { ... }` for injected `ExecOperations`.
 *
 * Gradle 8.11 deprecates `Project.exec(Action)`; 9.0 removes it. The file lives
 * under gitignored `gen/android`, so this rewrite runs after every init.
 *
 * @param {string} source raw BuildTask.kt
 * @returns {string}
 */
export function withExecOperations(source) {
  if (source.includes("execOperations.exec")) return source;
  if (!/\bproject\.exec\s*\{/.test(source)) {
    throw new Error("BuildTask.kt has no project.exec — did the Tauri template change?");
  }

  let next = source;
  if (!next.includes("import org.gradle.process.ExecOperations")) {
    if (!next.includes("import org.gradle.api.tasks.TaskAction")) {
      throw new Error("BuildTask.kt missing TaskAction import — cannot patch");
    }
    next = next.replace(
      /import org\.gradle\.api\.tasks\.TaskAction\r?\n/,
      (line) => `${line}import org.gradle.process.ExecOperations\nimport javax.inject.Inject\n`,
    );
  }

  if (!next.includes("abstract val execOperations")) {
    const classPat = /open class BuildTask\s*:\s*DefaultTask\(\)\s*\{/;
    if (!classPat.test(next)) {
      throw new Error("BuildTask.kt class header not recognised — cannot patch");
    }
    next = next.replace(
      classPat,
      "abstract class BuildTask : DefaultTask() {\n    @get:Inject\n    abstract val execOperations: ExecOperations\n",
    );
  }

  return next.replace(/\bproject\.exec\s*\{/g, "execOperations.exec {");
}

const BUILD_SRC_JVM17 = `
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}
`;

/**
 * Stop Kotlin from targeting the JDK that is running Gradle.
 *
 * `buildSrc` uses `kotlin-dsl` and inherits that JDK as `jvmTarget`. Kotlin
 * 1.9 cannot emit 23, so it warns and falls back to 22. Pin 17 to match the
 * plugin modules and ANDROID_SETUP.
 *
 * @param {string} source raw buildSrc/build.gradle.kts
 * @returns {string}
 */
export function withBuildSrcJvm17(source) {
  if (source.includes("JvmTarget.JVM_17")) return source;
  return `${source.trimEnd()}\n${BUILD_SRC_JVM17}`;
}

/** Major from a JDK `release` file (`JAVA_VERSION="25.0.2"` → 25). */
export function javaMajorFromRelease(text) {
  const match = /JAVA_VERSION="(\d+)/.exec(String(text ?? ""));
  return match ? Number(match[1]) : null;
}

/**
 * Gradle 8.14 + the Kotlin 1.9 `kotlin-dsl` in `buildSrc` know JVM 17–24.
 * 25 (current Android Studio JBR) configures with the error `25.0.2`.
 */
export function isUsableGradleJdk(major) {
  return Number.isInteger(major) && major >= 17 && major <= 24;
}

export function javaMajorFromHome(home) {
  if (!home) return null;
  const release = join(home, "release");
  if (!existsSync(release)) return null;
  try {
    return javaMajorFromRelease(readFileSync(release, "utf8"));
  } catch {
    return null;
  }
}

function defaultJdkHomes(env = process.env) {
  const pf = env["ProgramFiles"] || "C:\\Program Files";
  const homes = [];
  const javaDir = join(pf, "Java");
  if (existsSync(javaDir)) {
    for (const name of readdirSync(javaDir)) homes.push(join(javaDir, name));
  }
  homes.push(join(pf, "Android", "Android Studio", "jbr"));
  homes.push("/usr/lib/jvm/java-17-openjdk-amd64");
  homes.push("/usr/lib/jvm/java-21-openjdk-amd64");
  return homes;
}

/**
 * JDK Gradle should run on. `JAVA_HOME` wins when it is 17–24; otherwise the
 * lowest usable install (prefer 17 over 23). Studio JBR 25 is skipped.
 */
export function pickGradleJdkHome(env = process.env) {
  const consider = (home, into) => {
    if (!home) return;
    const major = javaMajorFromHome(home);
    if (!isUsableGradleJdk(major)) return;
    const javaBin = join(home, "bin", process.platform === "win32" ? "java.exe" : "java");
    if (!existsSync(javaBin)) return;
    into.push({ home, major });
  };
  const fromEnv = [];
  consider(env.JAVA_HOME, fromEnv);
  if (fromEnv.length) return fromEnv[0].home;
  const found = [];
  for (const home of defaultJdkHomes(env)) consider(home, found);
  found.sort((a, b) => a.major - b.major);
  return found[0]?.home ?? null;
}

export function withGradleJavaHome(properties, jdkHome) {
  const slash = String(jdkHome).replaceAll("\\", "/");
  const line = `org.gradle.java.home=${slash}`;
  if (/^org\.gradle\.java\.home=/m.test(properties)) {
    return properties.replace(/^org\.gradle\.java\.home=.*$/m, line);
  }
  return `${properties.trimEnd()}\n${line}\n`;
}

/** Env for `tauri android` so it does not pick Studio's JDK 25 JBR. */
export function gradleJdkEnv(jdkHome, env = process.env) {
  const bin = join(jdkHome, "bin");
  const sep = process.platform === "win32" ? ";" : ":";
  return {
    ...env,
    JAVA_HOME: jdkHome,
    PATH: `${bin}${sep}${env.PATH || ""}`,
  };
}

/**
 * Locate generated BuildTask.kt under buildSrc (package path varies).
 *
 * @returns {string | null}
 */
export function findBuildTaskKt(projectDir = PROJECT) {
  for (const root of [
    join(projectDir, "buildSrc", "src", "main", "java"),
    join(projectDir, "buildSrc", "src", "main", "kotlin"),
  ]) {
    if (!existsSync(root)) continue;
    const hits = readdirSync(root, { recursive: true }).filter((name) =>
      String(name).replaceAll("\\", "/").endsWith("BuildTask.kt"),
    );
    if (hits.length) return join(root, String(hits[0]));
  }
  return null;
}

function ensureAndroidProject() {
  if (existsSync(PROJECT)) return true;
  console.error(
    "no src-tauri/gen/android — running `tauri android init` (needs Android SDK, NDK, JDK 17+)...",
  );
  const result = spawnSync("npm", ["exec", "--", "tauri", "android", "init", "--ci"], {
    cwd: APP_DIR,
    stdio: "inherit",
    shell: true,
    env: process.env,
  });
  if ((result.status ?? 1) !== 0 || !existsSync(PROJECT)) {
    console.error(
      "tauri android init failed. Install the Android SDK, NDK, and JDK 17+, then from app/: `npm run android:init`.",
    );
    return false;
  }
  return true;
}

async function main() {
  if (!ensureAndroidProject()) {
    process.exitCode = 1;
    return;
  }

  await mkdir(RES_XML, { recursive: true });
  await copyFile(SOURCE, join(RES_XML, "network_security_config.xml"));

  const manifest = await readFile(MANIFEST, "utf8");
  const patched = withNetworkSecurityConfig(manifest);
  if (patched === manifest) {
    console.log("android overlay: config copied; manifest already references it");
  } else {
    await writeFile(MANIFEST, patched);
    console.log("android overlay: config copied and referenced from <application>");
  }

  const buildTask = findBuildTaskKt();
  if (!buildTask) {
    throw new Error("no BuildTask.kt under gen/android/buildSrc — is the project generated?");
  }
  const kotlin = await readFile(buildTask, "utf8");
  const kotlinPatched = withExecOperations(kotlin);
  if (kotlinPatched !== kotlin) {
    await writeFile(buildTask, kotlinPatched);
    console.log("android overlay: BuildTask.kt uses ExecOperations");
  }

  const buildSrcGradle = join(PROJECT, "buildSrc", "build.gradle.kts");
  if (existsSync(buildSrcGradle)) {
    const raw = await readFile(buildSrcGradle, "utf8");
    const next = withBuildSrcJvm17(raw);
    if (next !== raw) {
      await writeFile(buildSrcGradle, next);
      console.log("android overlay: buildSrc Kotlin jvmTarget 17");
    }
  }

  const jdk = pickGradleJdkHome();
  if (!jdk) {
    console.error(
      "android overlay: no JDK 17–24 for Gradle. Android Studio's JBR is 25.0.2;",
    );
    console.error(
      "Kotlin 1.9 then fails configuring :buildSrc with the error `25.0.2`.",
    );
    console.error("Install JDK 17, 21, or 23 and set JAVA_HOME, then retry.");
    process.exitCode = 1;
    return;
  }
  const propsPath = join(PROJECT, "gradle.properties");
  if (existsSync(propsPath)) {
    const props = await readFile(propsPath, "utf8");
    const next = withGradleJavaHome(props, jdk);
    if (next !== props) {
      await writeFile(propsPath, next);
      console.log(`android overlay: Gradle JDK ${javaMajorFromHome(jdk)} (${jdk.replaceAll("\\", "/")})`);
    }
  }
  const gradlew = join(PROJECT, process.platform === "win32" ? "gradlew.bat" : "gradlew");
  if (existsSync(gradlew)) {
    spawnSync(gradlew, ["--stop"], {
      cwd: PROJECT,
      stdio: "ignore",
      shell: process.platform === "win32",
      env: gradleJdkEnv(jdk),
    });
  }
}

// Only run when invoked as a script — the test imports the pure half.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main();
}
