/**
 * Apply the Android overlay to the generated Gradle project.
 *
 * `src-tauri/gen/android/` is generated by `tauri android init` and is not in
 * git. `android:apk:practice` / `android:apk:whiteboard` / `android:dev` /
 * `android-install-practice.cmd` call this first, so
 * a missing project runs `tauri android init --ci` instead of failing with a
 * "run init first" message.
 *
 * After init (or on every later build) the edits:
 *
 *   1. copy `android-overlay/network_security_config.xml` into the project's
 *      `res/xml/`,
 *   2. point the manifest's `<application>` at it, and
 *   3. rewrite generated `BuildTask.kt` so it uses `ExecOperations` instead of
 *      deprecated `Project.exec` (Gradle 8.11+ warning, gone in 9).
 *
 * Without (1)+(2) Android 9+ blocks the WebView's cleartext HTTP fetches to
 * external http:// pages (Annotate mode). The harness router itself is in-process.
 *
 * Idempotent: running it twice is a no-op, so it is safe to chain in front of
 * `tauri android dev` / `build`.
 */

import { spawnSync } from "node:child_process";
import { existsSync, readdirSync } from "node:fs";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(APP_DIR, "src-tauri", "android-overlay", "network_security_config.xml");
const PROJECT = join(APP_DIR, "src-tauri", "gen", "android");
const RES_XML = join(PROJECT, "app", "src", "main", "res", "xml");
const MANIFEST = join(PROJECT, "app", "src", "main", "AndroidManifest.xml");

const ATTRIBUTE = 'android:networkSecurityConfig="@xml/network_security_config"';

/**
 * Add the `networkSecurityConfig` attribute to `<application>`.
 *
 * Returns the manifest unchanged when the attribute is already there, so the
 * script can run before every build without accumulating duplicates.
 *
 * @param {string} manifest raw AndroidManifest.xml
 * @returns {string}
 */
export function withNetworkSecurityConfig(manifest) {
  if (manifest.includes("android:networkSecurityConfig")) return manifest;
  const opening = /<application\b/.exec(manifest);
  if (!opening) {
    throw new Error("AndroidManifest.xml has no <application> tag — is the project generated?");
  }
  const at = opening.index + opening[0].length;
  return `${manifest.slice(0, at)}\n        ${ATTRIBUTE}${manifest.slice(at)}`;
}

/**
 * Swap Tauri's generated `project.exec { ... }` for injected `ExecOperations`.
 *
 * Gradle 8.11 deprecates `Project.exec(Action)`; 9.0 removes it. The file lives
 * under gitignored `gen/android`, so this rewrite runs after every init.
 *
 * @param {string} source raw BuildTask.kt
 * @returns {string}
 */
export function withExecOperations(source) {
  if (source.includes("execOperations.exec")) return source;
  if (!/\bproject\.exec\s*\{/.test(source)) {
    throw new Error("BuildTask.kt has no project.exec — did the Tauri template change?");
  }

  let next = source;
  if (!next.includes("import org.gradle.process.ExecOperations")) {
    if (!next.includes("import org.gradle.api.tasks.TaskAction")) {
      throw new Error("BuildTask.kt missing TaskAction import — cannot patch");
    }
    next = next.replace(
      /import org\.gradle\.api\.tasks\.TaskAction\r?\n/,
      (line) => `${line}import org.gradle.process.ExecOperations\nimport javax.inject.Inject\n`,
    );
  }

  if (!next.includes("abstract val execOperations")) {
    const classPat = /open class BuildTask\s*:\s*DefaultTask\(\)\s*\{/;
    if (!classPat.test(next)) {
      throw new Error("BuildTask.kt class header not recognised — cannot patch");
    }
    next = next.replace(
      classPat,
      "abstract class BuildTask : DefaultTask() {\n    @get:Inject\n    abstract val execOperations: ExecOperations\n",
    );
  }

  return next.replace(/\bproject\.exec\s*\{/g, "execOperations.exec {");
}

/**
 * Locate generated BuildTask.kt under buildSrc (package path varies).
 *
 * @returns {string | null}
 */
export function findBuildTaskKt(projectDir = PROJECT) {
  for (const root of [
    join(projectDir, "buildSrc", "src", "main", "java"),
    join(projectDir, "buildSrc", "src", "main", "kotlin"),
  ]) {
    if (!existsSync(root)) continue;
    const hits = readdirSync(root, { recursive: true }).filter((name) =>
      String(name).replaceAll("\\", "/").endsWith("BuildTask.kt"),
    );
    if (hits.length) return join(root, String(hits[0]));
  }
  return null;
}

function ensureAndroidProject() {
  if (existsSync(PROJECT)) return true;
  console.error(
    "no src-tauri/gen/android — running `tauri android init` (needs Android SDK, NDK, JDK 17+)...",
  );
  const result = spawnSync("npm", ["exec", "--", "tauri", "android", "init", "--ci"], {
    cwd: APP_DIR,
    stdio: "inherit",
    shell: true,
    env: process.env,
  });
  if ((result.status ?? 1) !== 0 || !existsSync(PROJECT)) {
    console.error(
      "tauri android init failed. Install the Android SDK, NDK, and JDK 17+, then from app/: `npm run android:init`.",
    );
    return false;
  }
  return true;
}

async function main() {
  if (!ensureAndroidProject()) {
    process.exitCode = 1;
    return;
  }

  await mkdir(RES_XML, { recursive: true });
  await copyFile(SOURCE, join(RES_XML, "network_security_config.xml"));

  const manifest = await readFile(MANIFEST, "utf8");
  const patched = withNetworkSecurityConfig(manifest);
  if (patched === manifest) {
    console.log("android overlay: config copied; manifest already references it");
  } else {
    await writeFile(MANIFEST, patched);
    console.log("android overlay: config copied and referenced from <application>");
  }

  const buildTask = findBuildTaskKt();
  if (!buildTask) {
    throw new Error("no BuildTask.kt under gen/android/buildSrc — is the project generated?");
  }
  const kotlin = await readFile(buildTask, "utf8");
  const kotlinPatched = withExecOperations(kotlin);
  if (kotlinPatched !== kotlin) {
    await writeFile(buildTask, kotlinPatched);
    console.log("android overlay: BuildTask.kt uses ExecOperations");
  }
}

// Only run when invoked as a script — the test imports the pure half.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main();
}
