#!/usr/bin/env node
/**
 * Apply the Android overlay to the generated Gradle project.
 *
 * `src-tauri/gen/android/` is generated by `tauri android init` and is not in
 * git, so the two edits the app needs have to be re-applied after every init or
 * regeneration:
 *
 *   1. copy `android-overlay/network_security_config.xml` into the project's
 *      `res/xml/`, and
 *   2. point the manifest's `<application>` at it.
 *
 * Without them Android 9+ blocks the WebView's cleartext HTTP calls to
 * `lc serve` on the LAN and the app looks like it simply cannot reach the PC.
 *
 * Idempotent: running it twice is a no-op, so it is safe to chain in front of
 * `tauri android dev` / `build`.
 */

import { existsSync } from "node:fs";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const APP_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(APP_DIR, "src-tauri", "android-overlay", "network_security_config.xml");
const PROJECT = join(APP_DIR, "src-tauri", "gen", "android");
const RES_XML = join(PROJECT, "app", "src", "main", "res", "xml");
const MANIFEST = join(PROJECT, "app", "src", "main", "AndroidManifest.xml");

const ATTRIBUTE = 'android:networkSecurityConfig="@xml/network_security_config"';

/**
 * Add the `networkSecurityConfig` attribute to `<application>`.
 *
 * Returns the manifest unchanged when the attribute is already there, so the
 * script can run before every build without accumulating duplicates.
 *
 * @param {string} manifest raw AndroidManifest.xml
 * @returns {string}
 */
export function withNetworkSecurityConfig(manifest) {
  if (manifest.includes("android:networkSecurityConfig")) return manifest;
  const opening = /<application\b/.exec(manifest);
  if (!opening) {
    throw new Error("AndroidManifest.xml has no <application> tag — is the project generated?");
  }
  const at = opening.index + opening[0].length;
  return `${manifest.slice(0, at)}\n        ${ATTRIBUTE}${manifest.slice(at)}`;
}

async function main() {
  if (!existsSync(PROJECT)) {
    console.error(
      "no src-tauri/gen/android — run `npm run tauri android init` first (needs the Android SDK, NDK and JDK 17+).",
    );
    process.exitCode = 1;
    return;
  }

  await mkdir(RES_XML, { recursive: true });
  await copyFile(SOURCE, join(RES_XML, "network_security_config.xml"));

  const manifest = await readFile(MANIFEST, "utf8");
  const patched = withNetworkSecurityConfig(manifest);
  if (patched === manifest) {
    console.log("android overlay: config copied; manifest already references it");
    return;
  }
  await writeFile(MANIFEST, patched);
  console.log("android overlay: config copied and referenced from <application>");
}

// Only run when invoked as a script — the test imports the pure half.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  await main();
}
